Add test for cache-control: no-store
reaktivity/nukleus-http-cache.spec pull request #19
Opened 2017-09-07 07:24 UTC by stanculescu

2017-09-07 17:24 UTC, dpwspoon requested changes

2017-09-07 17:24 UTC, dpwspoon commented on src/main/scripts/org/reaktivity/specification/nukleus/http_cache/streams/proxy/cache.get.request.with.no-store/connect/server.rpt
> +                        ${http:header("cache-control", "max-age=15")}
This max-age is not on the other scripts for the first response.  The test will fail when you update the copy paste issue below because of this.  

I BELIEVE YOU WANT IT ON THE OTHER SCRIPTS to test the feature.  That is the max-age says the cache may store the response, but the no-store on the request explicitly says don't do this.   If this is an incorrect understanding of the SPEC/the intentions of this test, then please respond with your logic/understanding of the spec.

2017-09-07 17:24 UTC, dpwspoon commented on src/test/java/org/reaktivity/specification/nukleus/http_cache/streams/ProxyConnectCacheIT.java
> +            "${streams}/cache.get.request.with.no-store/accept/client",
copy paste issue, /accept/ => /connect/

2017-09-07 17:24 UTC, dpwspoon commented on src/main/scripts/org/reaktivity/specification/nukleus/http_cache/streams/proxy/cache.get.request.with.no-store/accept/client.rpt
> +read "hello world"
please change the make the response content of response 1 different than response 2.

I.E. change "hello world" to something like "response content 2" (don't forget to update the content length header if it is different)

2017-09-08 16:10 UTC, dpwspoon approved these changes

2017-09-11 17:58 UTC, dpwspoon commented
New test looks ok to me.

2017-09-12 23:46 UTC, jfallows approved these changes

2017-09-13 18:20 UTC, jfallows approved these changes

2017-09-13 22:49 UTC, merged