Tests for max-stale request cache-directive
reaktivity/nukleus-http-cache.spec pull request #21
Opened 2017-09-14 13:37 UTC by stanculescu

2017-09-20 16:50 UTC, dpwspoon requested changes
Very minor feedback.  LGTM.  Thanks

2017-09-20 16:50 UTC, dpwspoon commented on src/main/scripts/org/reaktivity/specification/nukleus/http_cache/streams/proxy/cache.max-stale.no.value/accept/client.rpt
> +                        ${http:header("cache-control", "max-age=1, max-stale")}
why does this have the max-age directive?  Does the spec specify what we should do if there is both of these and which one takes precident?

2017-09-20 16:50 UTC, dpwspoon commented on src/main/scripts/org/reaktivity/specification/nukleus/http_cache/streams/proxy/cache.max-stale.no.value/accept/client.rpt
> +                        ${http:header("cache-control", "max-age=1, max-stale")}
Section 5.2.1.1.
```
5.2.1.1.  max-age

   Argument syntax:

      delta-seconds (see Section 1.2.1)

   The "max-age" request directive indicates that the client is
   unwilling to accept a response whose age is greater than the
   specified number of seconds.  Unless the max-stale request directive
   is also present, the client is not willing to accept a stale
   response.

   This directive uses the token form of the argument syntax: e.g.,
   'max-age=5' not 'max-age="5"'.  A sender SHOULD NOT generate the
   quoted-string form.
```

But it seems like you already have a test for that below, so probably no need for that.

2017-09-20 16:50 UTC, dpwspoon commented on src/main/scripts/org/reaktivity/specification/nukleus/http_cache/streams/proxy/cache.max-stale/accept/client.rpt
> +#
nit, consider renaming this script cache.max-stale.with.value to be inline with the without value script

2017-09-20 16:50 UTC, dpwspoon commented on src/main/scripts/org/reaktivity/specification/nukleus/http_cache/streams/proxy/expire.max-stale/accept/client.rpt
> +connect await CACHE_EXPIRED
nit: consider renaming property CACHE_EXPIRED_AND_STALE_FOR_2_SECONDS or something like that??

2017-09-20 16:51 UTC, dpwspoon commented
Very thorough set of test cases.  Thanks @stanculescu

2017-09-22 22:59 UTC, dpwspoon submitted a review, later dismissed

2017-10-02 04:20 UTC, akrambek commented on src/main/scripts/org/reaktivity/specification/nukleus/http_cache/streams/proxy/cache.max-stale.no.value/accept/client.rpt
> +
If the max-age is 15 seconds and not yet expired I wonder it should receive `Response is Stale` response. By looking into implementation code test `shouldCacheMaxStaleWithNoValue` from `nukleus-http-cache.java` it looks like you meant `max-age=1` and if so why is this passing? Would you please clarify this?

2017-10-02 04:20 UTC, akrambek commented on src/main/scripts/org/reaktivity/specification/nukleus/http_cache/streams/proxy/cache.max-stale.no.value/accept/client.rpt
> +
I think it makes sense to add another Input Stream to test if it is working for any age as specified in the rfc which makes test case complete.

2017-10-11 16:38 UTC, merged