Add tests on min-fresh request cache-directive
reaktivity/nukleus-http-cache.spec pull request #24
Opened 2017-09-19 13:59 UTC by stanculescu

2017-09-20 16:55 UTC, dpwspoon commented on src/main/scripts/org/reaktivity/specification/nukleus/http_cache/streams/proxy/cache.min-fresh.with.max-age/accept/client.rpt
> +                        ${http:header("cache-control", "max-age=5, min-fresh=2")}
Does the spec talk about clients sending both of these?  Is there an edge case where we need a test that has both?

2017-09-20 17:24 UTC, dpwspoon requested changes
I don't see/understand the need to test the max-age and min-fresh request cache-directive together.  Maybe I'm missing something?

If not, then I think you only need to sets of tests, one for expire min-fresh and one for testing min-fresh

2017-09-20 17:24 UTC, dpwspoon commented on src/main/scripts/org/reaktivity/specification/nukleus/http_cache/streams/proxy/expire.min-fresh/accept/client.rpt
> +connect await CACHE_EXPIRED
This doesn't even to wait here, does it?  
```
   The "min-fresh" request directive indicates that the client is
   willing to accept a response whose freshness lifetime is no less than
   its current age plus the specified time in seconds.  That is, the
   client wants a response that will still be fresh for at least the
   specified number of seconds.
```

So if you change the min-fresh settings to 6 below, then there is no need for this barrier I believe??

2017-09-21 13:02 UTC, stanculescu commented
You're right, it's no need to use max-age and min-fresh request cache-directive together. I updated the PR with the feedback implementation. Thanks @dpwspoon

2017-09-21 15:57 UTC, dpwspoon requested changes
One minor request to change

2017-09-21 15:57 UTC, dpwspoon commented on src/main/scripts/org/reaktivity/specification/nukleus/http_cache/streams/proxy/cache.min-fresh/accept/client.rpt
> +connect await CACHE_EXPIRED
I don't think you need this barrier "CACHE_EXPIRED" for this test as this is a test to see that it hits.  Also, it should be fine but you are racing the system, max-age=3 min-fresh=2 so 1 second for delay.  I'd suggest changing the max-age on the response to 15, and the min fresh on the second response being 5 or 10

2017-09-21 15:57 UTC, dpwspoon commented on src/main/scripts/org/reaktivity/specification/nukleus/http_cache/streams/proxy/expire.min-fresh/accept/client.rpt
> +read nukleus:begin.ext ${http:header(":status", "200")}
LGTM

2017-09-22 22:59 UTC, dpwspoon approved these changes

2017-10-02 13:06 UTC, akrambek commented on src/main/scripts/org/reaktivity/specification/nukleus/http_cache/streams/proxy/cache.min-fresh/accept/client.rpt
> +
In my opinion this test is a bit weak and doesn't really test the min-fresh even removing `"min-fresh=5` will make the test to pass. I believe this write option should somewhere in between max-age and min-fresh to really test min-fresh got applied correctly. For example, if the current `age` is 10 and `min-fresh=5` we need to send request after 11 seconds to make sure that both current age and min-fresh applied.

2017-10-11 16:38 UTC, merged