[Dont' merge yet] Added tests for Storing Incomplete Responses
reaktivity/nukleus-http-cache.spec pull request #32
Opened 2017-10-23 17:46 UTC by akrambek

2017-11-09 00:53 UTC, dpwspoon requested changes

2017-11-09 00:53 UTC, dpwspoon commented on src/main/scripts/org/reaktivity/specification/nukleus/http_cache/streams/proxy/cache.incomplete.response.with.range/accept/client.rpt
> +                        ${http:header(":content-range", "bytes 0-5/11")}
I don't think content-range is a pseudo header

2017-11-09 00:53 UTC, dpwspoon commented on src/main/scripts/org/reaktivity/specification/nukleus/http_cache/streams/proxy/cache.incomplete.response.with.range/accept/client.rpt
> +                        ${http:header(":content-range", "bytes 0-5/11")}
I believe the request uses the Range header "Range: bytes=0-1023" and the response sends the content-range header??

2017-11-09 00:53 UTC, dpwspoon commented on src/main/scripts/org/reaktivity/specification/nukleus/http_cache/streams/proxy/cache.incomplete.response.with.range/accept/client.rpt
> +                       ${http:header("last-modified", date)}
missing content-range headers

2017-11-09 00:53 UTC, dpwspoon commented on src/main/scripts/org/reaktivity/specification/nukleus/http_cache/streams/proxy/cache.incomplete.response.with.range/connect/server.rpt
> +write close
nit, newline here and below

2017-11-30 10:25 UTC, akrambek commented
I am closing this PR since we are not going to implement it yet.

2017-11-30 10:25 UTC, closed without merging