Push promise requests won't have have authorization header
reaktivity/nukleus-http-cache.spec pull request #52
Opened 2018-06-25 17:45 UTC by jitsni

Push promise requests won't have have authorization header (instead
authorization bit mask is sent in the DATA frame)

2018-06-25 17:57 UTC, dpwspoon commented
I think we need a test (or 2) where when a push promise has the authorization header removed, the response to that push promise MUST have the private cache-control header set (if the cache-control header on the response did not have public set)

2018-06-25 18:00 UTC, dpwspoon commented
I think we need a test that shows we aren't propagating responses that introduce a vary header to push promises that have now removed their vary header.  Likewise, if there is a vary header that matches, we probably need to forward that header on the request.

2018-06-27 21:00 UTC, dpwspoon requested changes

2018-06-27 21:00 UTC, dpwspoon commented on src/main/scripts/org/reaktivity/specification/nukleus/http_cache/streams/proxy/edge-arch/polling.vary.header.mismatch/connect/client.rpt
> +                             .item("etag", etag)
I think this is missing `.item("vary", "user-agent")`, there are other things missing on a few of the vary tests, but I think the other tests (cache-control private for authentication) looks good.

For the vary header, we still need to solve for push promises that are late in the wrap around from h2, and have had their headers stripped.  Potentially to null values that match the stored response but not the wrapped around response.  Additionally, we need to have a test for Vary: "*"

[Link to spec](https://tools.ietf.org/html/rfc7231#section-7.1.4): https://tools.ietf.org/html/rfc7231#section-7.1.4

2018-07-06 17:30 UTC, jfallows approved these changes

2018-07-06 18:52 UTC, jitsni commented on src/main/scripts/org/reaktivity/specification/nukleus/http_cache/streams/proxy/edge-arch/polling.vary.header.mismatch/connect/client.rpt
> +                             .item("etag", etag)
Fixed vary header tests and also added a test for vary: *

2018-07-06 19:08 UTC, jfallows approved these changes

2018-07-06 19:09 UTC, jfallows commented
All feedback has been applied.

2018-07-06 19:09 UTC, merged